### ISSUE TITLE
Setup deployment workflow and secrets

### ISSUE THREAD

**Issue by Vostos007** [Vostos007/Bot-2.0#2]
Необходимо добавить следующие секреты в Settings -> Secrets and variables -> Actions:

1. SERVER_HOST: [IP вашего сервера]
2. SERVER_USERNAME: root
3. SERVER_SSH_KEY: [Ваш приватный SSH ключ]

Также нужно создать файл `.github/workflows/deploy.yml` со следующим содержимым:

```yaml
name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/telegram-bot
            git pull origin main
```

После настройки секретов и добавления файла workflow, автоматический деплой будет работать при каждом push в main ветку.
